export const GET_SPECIFICATIONS = "GET_SPECIFICATIONS";
export const UPDATE_STOCK = "UPDATE_STOCK";

export const CREATE_SPECIFICATION_REQUEST = "CREATE_SPECIFICATION_REQUEST";
export const CREATE_SPECIFICATION_SUCCESS = "CREATE_SPECIFICATION_SUCCESS";
export const CREATE_SPECIFICATION_FAILURE = "CREATE_SPECIFICATION_FAILURE";

export const CREATE_SPECIFICATION_CATEGORY_REQUEST =
  "CREATE_SPECIFICATION_CATEGORY_REQUEST";
export const CREATE_SPECIFICATION_CATEGORY_SUCCESS =
  "CREATE_SPECIFICATION_CATEGORY_SUCCESS";
export const CREATE_SPECIFICATION_CATEGORY_FAILURE =
  "CREATE_SPECIFICATION_CATEGORY_FAILURE";

export const GET_SPECIFICATION_CATEGORY_REQUEST =
  "GET_SPECIFICATION_CATEGORY_REQUEST";
export const GET_SPECIFICATION_CATEGORY_SUCCESS =
  "GET_SPECIFICATION_CATEGORY_SUCCESS";
export const GET_SPECIFICATION_CATEGORY_FAILURE =
  "GET_SPECIFICATION_CATEGORY_FAILURE";
