export const CREATE_SHOP_REQUEST = "CREATE_SHOP_REQUEST";
export const CREATE_SHOP_SUCCESS = "CREATE_SHOP_SUCCESS";
export const CREATE_SHOP_FAILURE = "CREATE_SHOP_FAILURE";

export const GET_ALL_SHOPS_REQUEST = "GET_ALL_SHOPS_REQUEST";
export const GET_ALL_SHOPS_SUCCESS = "GET_ALL_SHOPS_SUCCESS";
export const GET_ALL_SHOPS_FAILURE = "GET_ALL_SHOPS_FAILURE";

export const DELETE_SHOP_REQUEST = "DELETE_SHOP_REQUEST";
export const DELETE_SHOP_SUCCESS = "DELETE_SHOP_SUCCESS";
export const DELETE_SHOP_FAILURE = "DELETE_SHOP_FAILURE";

export const UPDATE_SHOP_REQUEST = "UPDATE_SHOP_REQUEST";
export const UPDATE_SHOP_SUCCESS = "UPDATE_SHOP_SUCCESS";
export const UPDATE_SHOP_FAILURE = "UPDATE_SHOP_FAILURE";

export const GET_SHOP_BY_ID_REQUEST = "GET_SHOP_BY_ID_REQUEST";
export const GET_SHOP_BY_ID_SUCCESS = "GET_SHOP_BY_ID_SUCCESS";
export const GET_SHOP_BY_ID_FAILURE = "GET_SHOP_BY_ID_FAILURE";

export const GET_SHOP_BY_USER_ID_REQUEST = "GET_SHOP_BY_USER_ID_REQUEST";
export const GET_SHOP_BY_USER_ID_SUCCESS = "GET_SHOP_BY_USER_ID_SUCCESS";
export const GET_SHOP_BY_USER_ID_FAILURE = "GET_SHOP_BY_USER_ID_FAILURE";

export const UPDATE_SHOP_STATUS_REQUEST = "UPDATE_SHOP_STATUS_REQUEST";
export const UPDATE_SHOP_STATUS_SUCCESS = "UPDATE_SHOP_STATUS_SUCCESS";
export const UPDATE_SHOP_STATUS_FAILURE = "UPDATE_SHOP_STATUS_FAILURE";

export const CREATE_EVENTS_REQUEST = "CREATE_EVENTS_REQUEST";
export const CREATE_EVENTS_SUCCESS = "CREATE_EVENTS_SUCCESS";
export const CREATE_EVENTS_FAILURE = "CREATE_EVENTS_FAILURE";

export const GET_ALL_EVENTS_REQUEST = "GET_ALL_EVENTS_REQUEST";
export const GET_ALL_EVENTS_SUCCESS = "GET_ALL_EVENTS_SUCCESS";
export const GET_ALL_EVENTS_FAILURE = "GET_ALL_EVENTS_FAILURE";

export const DELETE_EVENTS_REQUEST = "DELETE_EVENTS_REQUEST";
export const DELETE_EVENTS_SUCCESS = "DELETE_EVENTS_SUCCESS";
export const DELETE_EVENTS_FAILURE = "DELETE_EVENTS_FAILURE";

export const GET_SHOPS_EVENTS_REQUEST = "GET_SHOPS_EVENTS_REQUEST";
export const GET_SHOPS_EVENTS_SUCCESS = "GET_SHOPS_EVENTS_SUCCESS";
export const GET_SHOPS_EVENTS_FAILURE = "GET_SHOPS_EVENTS_FAILURE";

export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAILURE = "CREATE_CATEGORY_FAILURE";

export const GET_SHOPS_CATEGORY_REQUEST = "GET_SHOPS_CATEGORY_REQUEST";
export const GET_SHOPS_CATEGORY_SUCCESS = "GET_SHOPS_CATEGORY_SUCCESS";
export const GET_SHOPS_CATEGORY_FAILURE = "GET_SHOPS_CATEGORY_FAILURE";
