export const GET_SHOPS_ORDERS_REQUEST = "GET_SHOPS_ORDERS_REQUEST";
export const GET_SHOPS_ORDERS_SUCCESS = "GET_SHOPS_ORDERS_SUCCESS";
export const GET_SHOPS_ORDERS_FAILURE = "GET_SHOPS_ORDERS_FAILURE";

export const UPDATE_ORDER_STATUS_REQUEST = "UPDATE_ORDER_STATUS_REQUEST";
export const UPDATE_ORDER_STATUS_SUCCESS = "UPDATE_ORDER_STATUS_SUCCESS";
export const UPDATE_ORDER_STATUS_FAILURE = "UPDATE_ORDER_STATUS_FAILURE";
